### ISSUE TITLE
Safe SDK Bug: Txn executes successfully from the ui, however not from the executeTransaction method of safeSDK

### ISSUE THREAD

**Issue by DecoratedWings** [safe-global/safe-core-sdk#222]
## Description

I have the following issue: 

- I have my dapp create, sign, and propose a transaction to gnosis safe using safe-core-sdk. 

- I then approve this transaction from another dapp as a user (both addresses are owners in the multisig).

(To be more specific the transaction is to call a method from my team's own smart contract.)

- On gnosis ui I see that I have 2 approvals, great. 

- When I go to execute the transaction using safeSdk.executeTransaction() I receive an error:

```
 error: Error: execution reverted: GS026
```

- When I manually execute the transaction on the ui, it completes fine, here's is an example:
https://goerli.etherscan.io/tx/0x2dae93f1e2769008aeb5a63b123a1188a9e6dc21649e2bc7d32e0821fa069657

**- It appears to be related to the following bug: https://github.com/safe-global/web-core/issues/710**

- I have pasted the logs below our team would really like to get this working as soon as possible to meet internal deadlines, thank you in advance for your time. 

## Environment

- Safe Core SDK version: 2.2.1
- Safe contract version: [1.3.0+L2]
- Environment:
  - non-browser 

## Steps to reproduce

Here is my goerli safe: https://gnosis-safe.io/app/gor:0x53f4be91b094a1B26CAd225937dD9179D42604D7/transactions/queue
The most recent completed transactions in the history executed correctly when manually executed.

## Expected result

Expected executeTransaction to work given that the transaction executing from the gnosis safe ui is working. 

## Additional context

Error log from safeSdk.executeTransaction():

**PLEASE NOTE THE GS026 ERROR CODE WHICH ISN'T APPEARING ON THE UI, UI HAS GREEN TENDERLY SIMULATION AND TRANSACTIONS EXECUTE FINE.**

```
ChainID is:  5
SafeSDK:  0x0106bEC64f321796B9b79E8c81aE8f58F2e83f48
Safe Owners:  [
  '0x0DB6854c93bf578f6fA2962decF92eD0D08474c1',
  '0x47430D6f05f1A10484B1082ec27883002eA1eE1F'
]

SAFE CONFIRMATIONS:  [
  {
    owner: '0x0DB6854c93bf578f6fA2962decF92eD0D08474c1',
    submissionDate: '2022-07-22T21:31:09.950415Z',
    transactionHash: null,
    signature: '0x1916d438094fa135f21ac8badcca661897da729101e59e2edcdbcc5303f2d91e6e610a3b687ae62ff6bc0996590130fd5537fb73e521fb16e392ef74468ae05b1f',
    signatureType: 'ETH_SIGN'
  },
  {
    owner: '0x47430D6f05f1A10484B1082ec27883002eA1eE1F',
    submissionDate: '2022-07-22T21:36:13.075734Z',
    transactionHash: null,
    signature: '0xcaf960932f7b961c59f89067cf6ae376b7920bc8024c03baebdf7686817f25c57cdb84c5dad3e6fc1a906c9f43cd24448940afc7cec5bd1f20cbb63b499e3b661f',
    signatureType: 'ETH_SIGN'
  }
]


Unable to execute safeTransaction
Error occurred:  Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":75,\"error\":{\"code\":3,\"message\":\"execution reverted: **GS026**\",\"data\":\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000054753303236000000000000000000000000000000000000000000000000000000\"}}","error":{"code":3,"data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000054753303236000000000000000000000000000000000000000000000000000000"},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"from\":\"0x0db6854c93bf578f6fa2962decf92ed0d08474c1\",\"to\":\"0x53f4be91b094a1b26cad225937dd9179d42604d7\",\"data\":\"0x6a761202000000000000000000000000f37d57b9b32b671b6e7bc1ee8619d64dec7f294c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ba43b7400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000846df9f6ec00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000090000000000000000000000000000000700000000000000000000000047430d6f05f1a10484b1082ec27883002ea1ee1f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000820000000000000000000000000db6854c93bf578f6fa2962decf92ed0d08474c1000000000000000000000000000000000000000000000000000000000000000001caf960932f7b961c59f89067cf6ae376b7920bc8024c03baebdf7686817f25c57cdb84c5dad3e6fc1a906c9f43cd24448940afc7cec5bd1f20cbb63b499e3b661f000000000000000000000000000000000000000000000000000000000000\"}],\"id\":75,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://eth-goerli.g.alchemy.com/v2/WR-zKI2UmwzeCNAz5dZDInT7-EwUoEJl"}, method="estimateGas", transaction={"from":"0x0DB6854c93bf578f6fA2962decF92eD0D08474c1","to":"0x53f4be91b094a1B26CAd225937dD9179D42604D7","data":"0x6a761202000000000000000000000000f37d57b9b32b671b6e7bc1ee8619d64dec7f294c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ba43b7400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000846df9f6ec00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000090000000000000000000000000000000700000000000000000000000047430d6f05f1a10484b1082ec27883002ea1ee1f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000820000000000000000000000000db6854c93bf578f6fa2962decf92ed0d08474c1000000000000000000000000000000000000000000000000000000000000000001caf960932f7b961c59f89067cf6ae376b7920bc8024c03baebdf7686817f25c57cdb84c5dad3e6fc1a906c9f43cd24448940afc7cec5bd1f20cbb63b499e3b661f000000000000000000000000000000000000000000000000000000000000","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.6.1)

at Logger.makeError (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at checkError (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:80:16)
    at JsonRpcProvider.<anonymous> (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:562:20)
    at step (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":75,\"error\":{\"code\":3,\"message\":\"execution reverted: GS026\",\"data\":\"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000054753303236000000000000000000000000000000000000000000000000000000\"}}", error={"code":3,"data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000054753303236000000000000000000000000000000000000000000000000000000"}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"from\":\"0x0db6854c93bf578f6fa2962decf92ed0d08474c1\",\"to\":\"0x53f4be91b094a1b26cad225937dd9179d42604d7\",\"data\":\"0x6a761202000000000000000000000000f37d57b9b32b671b6e7bc1ee8619d64dec7f294c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ba43b7400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000846df9f6ec00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000090000000000000000000000000000000700000000000000000000000047430d6f05f1a10484b1082ec27883002ea1ee1f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000820000000000000000000000000db6854c93bf578f6fa2962decf92ed0d08474c1000000000000000000000000000000000000000000000000000000000000000001caf960932f7b961c59f89067cf6ae376b7920bc8024c03baebdf7686817f25c57cdb84c5dad3e6fc1a906c9f43cd24448940afc7cec5bd1f20cbb63b499e3b661f000000000000000000000000000000000000000000000000000000000000\"}],\"id\":75,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://eth-goerli.g.alchemy.com/v2/WR-zKI2UmwzeCNAz5dZDInT7-EwUoEJl", code=SERVER_ERROR, version=web/5.6.1)
      at Logger.makeError (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
      at Logger.throwError (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
      at /Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/web/src.ts/index.ts:329:28
      at step (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"jsonrpc":"2.0","id":75,"error":{"code":3,"message":"execution reverted: GS026","data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000054753303236000000000000000000000000000000000000000000000000000000"}}',
    error: Error: execution reverted: GS026
        at getResult (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:97:28)
        at processJsonFunc (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/web/src.ts/index.ts:371:22)
        at /Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/web/src.ts/index.ts:308:42
        at step (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/web/lib/index.js:33:23)
        at Object.next (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/web/lib/index.js:14:53)
        at fulfilled (/Users/mona/Documents/dev-OneOf/polygon-express-app/node_modules/@ethersproject/web/lib/index.js:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      code: 3,
      data: '0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000054753303236000000000000000000000000000000000000000000000000000000'
    },
    requestBody: '{"method":"eth_estimateGas","params":[{"from":"0x0db6854c93bf578f6fa2962decf92ed0d08474c1","to":"0x53f4be91b094a1b26cad225937dd9179d42604d7","data":"0x6a761202000000000000000000000000f37d57b9b32b671b6e7bc1ee8619d64dec7f294c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ba43b7400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000846df9f6ec00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000090000000000000000000000000000000700000000000000000000000047430d6f05f1a10484b1082ec27883002ea1ee1f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000820000000000000000000000000db6854c93bf578f6fa2962decf92ed0d08474c1000000000000000000000000000000000000000000000000000000000000000001caf960932f7b961c59f89067cf6ae376b7920bc8024c03baebdf7686817f25c57cdb84c5dad3e6fc1a906c9f43cd24448940afc7cec5bd1f20cbb63b499e3b661f000000000000000000000000000000000000000000000000000000000000"}],"id":75,"jsonrpc":"2.0"}',
    requestMethod: 'POST',
    url: 'https://eth-goerli.g.alchemy.com/v2/WR-zKI2UmwzeCNAz5dZDInT7-EwUoEJl'
  },
  method: 'estimateGas',
  transaction: {
    from: '0x0DB6854c93bf578f6fA2962decF92eD0D08474c1',
    to: '0x53f4be91b094a1B26CAd225937dD9179D42604D7',
    data: '0x6a761202000000000000000000000000f37d57b9b32b671b6e7bc1ee8619d64dec7f294c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ba43b7400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000846df9f6ec00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000090000000000000000000000000000000700000000000000000000000047430d6f05f1a10484b1082ec27883002ea1ee1f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000820000000000000000000000000db6854c93bf578f6fa2962decf92ed0d08474c1000000000000000000000000000000000000000000000000000000000000000001caf960932f7b961c59f89067cf6ae376b7920bc8024c03baebdf7686817f25c57cdb84c5dad3e6fc1a906c9f43cd24448940afc7cec5bd1f20cbb63b499e3b661f000000000000000000000000000000000000000000000000000000000000',
    accessList: null
  }
}
```

**Comment by DecoratedWings** [comment]
@germartinez 
Apologies to tag, but can this kindly be looked into by the team? It's blocking our team from executing transactions from the SDK on goerli. 
Kind Regards and Thanks!

**Comment by DecoratedWings** [comment]
fixed with: https://github.com/safe-global/web-core/issues/710
