### ISSUE TITLE
`request to '' failed, reason: read ECONNRESET` when using api-kit

### ISSUE THREAD

**Issue by codeonblocks** [safe-global/safe-core-sdk#501]
## Description

Whenever I try to call the code below it fails to execute and throws the error I pasted below. It works on my computer, but it doesn't work when the code is on Azure. I'm able to view the results if I paste the URL it's trying to call into the browser, but not when it's being called from the `safeSdk`.

```typescript
const safeTransaction = await safeSdk.createTransaction({
  safeTransactionData: {
    to,
    value,
    data,
    nonce: await safeService.getNextNonce(safeAddress),
  },
});
```

```error
FetchError: request to https://safe-transaction-goerli.safe.global/api/v1/safes/0xA7655De6F6Ea6B7f10791CCD93318aB8014a0405/ failed, reason: read ECONNRESET

  at ClientRequest.<anonymous> (/home/site/wwwroot/node_modules/node-fetch/lib/index.js:1505:11)
  at ClientRequest.clsBind (/agents/nodejs/node_modules/cls-hooked/context.js:172:17)
  at ClientRequest.emit (node:events:525:35)
  at ClientRequest.emitted (/agents/nodejs/node_modules/emitter-listener/listener.js:134:21)
  at TLSSocket.socketErrorListener (node:_http_client:502:9)
  at TLSSocket.emit (node:events:513:28)
  at emitErrorNT (node:internal/streams/destroy:151:8)
  at emitErrorCloseNT (node:internal/streams/destroy:116:3)
  at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    type: 'system',
    errno: 'ECONNRESET',
    code: 'ECONNRESET' 
  }
```

## Environment

- Safe Core SDK version: 
  `"@safe-global/api-kit": "^1.3.0"`,
  `"@safe-global/protocol-kit": "^1.2.0"`,
  `"@safe-global/safe-core-sdk-types": "^2.2.0"`
- Environment:
  - non-browser, using Node.js v18.16.0

## Steps to reproduce

```typescript
const safeAddress = await safeSdk.getAddress();

// Fails here in prod
const safeTransaction = await safeSdk.createTransaction({
  safeTransactionData: {
    to,
    value,
    data,
    nonce: await safeService.getNextNonce(safeAddress),
  },
});
```

## Expected result

It should work as normal and allow me to create the transaction.

## Other context
![image](https://github.com/safe-global/safe-core-sdk/assets/32179921/74d13ee8-42d9-472f-934d-0153f2331422)

**Comment by codeonblocks** [comment]
![image](https://github.com/safe-global/safe-core-sdk/assets/32179921/5499d061-fb72-450e-b23a-dbedebf8b040)

**Comment by codeonblocks** [comment]
Issue was with company's Azure firewall configuration.
