### ISSUE TITLE
Deploy safe fails to confirm on latest version with ethers v6

### ISSUE THREAD

**Issue by froggiedev** [safe-global/safe-core-sdk#623]
Expected behavior: Safe is deployed, then receipt is confirmed and returned
Current behavior: Safe is deployed, but the receipt fails to be confirmed with the following error:

```
TypeError: receipt.confirmations is not a function
    at ContractTransactionResponse.wait (provider.js:1066:1)
    at async ContractTransactionResponse.wait (wrappers.js:115:1)
    at async eval (SafeProxyFactoryEthersContract.js:27:1)
    at async SafeFactory.deploySafe (index.js:101:1)
```

Reproducing code:

`"ethers": "^6.7.1"`
`@safe-global/protocol-kit": "^2.0.0`

```
import { ethers } from 'ethers';
import {
  SafeFactory,
  SafeAccountConfig,
  EthersAdapter,
} from '@safe-global/protocol-kit';

  const ethAdapter = new EthersAdapter({
      ethers,
      signerOrProvider: sdk.signer, // ethers v6 `Signer`
  });

  const safeAccountConfig: SafeAccountConfig = {
      owners: [sdk.signerAddress],
      threshold: 1,
    }

  async function deploySafe() {
    const safeFactory = await SafeFactory.create({ ethAdapter });

    const safeSDK = await safeFactory.deploySafe({
      safeAccountConfig,
      saltNonce: safeDeploymentConfig.saltNonce,
    });
    const safeAddress = await safeSDK.getAddress();

    console.log('Your Safe has been deployed:');
    console.log(`https://arbiscan.io/address/${safeAddress}`);
    console.log(`https://app.safe.global/arb1:${safeAddress}`);

    return safeSDK;
}
```

**Comment by dasanra** [comment]
@froggiedev thank you for your report. Could you also share which chain, Safe version and RPC provider you were using? 

Thank you!

**Comment by froggiedev** [comment]
> @froggiedev thank you for your report. Could you also share which chain, Safe version and RPC provider you were using?
> 
> Thank you!

Chain: Arbitrum Goerli
Safe Version: 1.4.1 (package version shared above)
RPC Provider: Quicknode

**Comment by dasanra** [comment]
@froggiedev as far as I checked the issue is not coming from `ethers v6` migration but because the Arbitrum contracts v1.4.1 are not yet on safe-deployments and we are not correctly handling this. You shouldn't find this issue if you try to deploy the contract v1.3.0. We will investigate further.

**Comment by froggiedev** [comment]
> @froggiedev as far as I checked the issue is not coming from `ethers v6` migration but because the Arbitrum contracts v1.4.1 are not yet on safe-deployments and we are not correctly handling this. You shouldn't find this issue if you try to deploy the contract v1.3.0. We will investigate further.

Does contract v1.3.0 work with ethers v6?

**Comment by dasanra** [comment]
Yes, you can safely use ethers v6 in the `safe-core-sdk` and v1.3.0 version of the smart contracts

**Comment by froggiedev** [comment]
> Yes, you can safely use ethers v6 in the `safe-core-sdk` and v1.3.0 version of the smart contracts

Ah, but v1.3.0 does not support the Safe ERC-4337 module if I remember correctly.

**Comment by dasanra** [comment]
The issue should be now solved for Arbitrum, as the addresses are available at `safe-deployments` package.

Also [this ticket](https://github.com/safe-global/safe-core-sdk/issues/650) relates better to the issue that causes this unexpected behavior.
